# Generated by Django 6.0.4 on 2026-04-19 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_nama_created_at_nama_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nama',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
        migrations.AlterField(
            model_name='nama',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
